const ACTION_TYPE = {
  INIT_AUTH: "INIT_AUTH",
  RESET_AUTH: "RESET_AUTH",
  FILTER_BY_CATEGORY: "FILTER_BY_CATEGORY",
  MANAGE_LIKES: "MANAGE_LIKES",
  MANAGE_PLAYLIST: "MANAGE_PLAYLIST",
  MANAGE_HISTORY: "MANAGE_HISTORY",
  MANAGE_WATCH_LATER: "MANAGE_WATCH_LATER",
  MANAGE_SINGLE_PLAYLIST: "MANAGE_SINGLE_PLAYLIST"
};

export { ACTION_TYPE };
